version: '3.9'

services:
    # 前端服务
    frontend:
        container_name: ssr-frontend-docker
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - '3003:80'
        networks:
            - app-network
        environment:
            - NODE_ENV=production

    # 后端服务
    backend:
        container_name: ssr-backend-docker
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - '3011:3011'
        networks:
            - app-network

# 网络
networks:
    app-network:
        driver: bridge
