version: '3.9'

services:
    # 前端服务
    frontend:
        container_name: ssr-frontend-docker
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - '3010:3010'
        networks:
            - app-network
        environment:
            - NODE_ENV=production
            - NITRO_PORT=3010
        restart: always

    # 后端服务
    backend:
        container_name: ssr-backend-docker
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - '3011:3011'
        networks:
            - app-network
        restart: always

# 网络
networks:
    app-network:
        driver: bridge
